stages:
- stage: Deploy
  jobs:
  - job: Deploy
    
    pool:
      vmImage: 'Ubuntu-16.04'
    
    steps:
     - task: AzureResourceManagerTemplateDeployment@3
    inputs:
      deploymentScope: 'Resource Group'
      azureResourceManagerConnection: 'AzurePipelineConnection'
      subscriptionId: '2ea029b5-e345-4844-a5a8-15dadf4e985f'
      action: 'Create Or Update Resource Group'
      resourceGroupName: '$(resourcegroup)'
      location: 'East US'
      templateLocation: 'URL of the file'
      csmFileLink: 'https://raw.githubusercontent.com/mayhashah7/ContosoAir/master/deployment/azuredeploy.json'
      csmParametersFileLink: 'https://raw.githubusercontent.com/mayhashah7/ContosoAir/master/deployment/azuredeploy.parameters.json'
      overrideParameters: '-p_environment mayhashah'
      deploymentMode: 'Incremental'
      
  - task: AzureRmWebAppDeployment@4
    inputs:
      ConnectionType: 'AzureRM'
      azureSubscription: 'AzurePipelineConnection'
      appType: 'webApp'
      WebAppName: 'githubci-web-mayhashah'
      packageForLinux: '$(build.artifactstagingdirectory)/**/*.zip'