stages:
- stage: Deploy
  jobs:
  - job: Deploy
    
    pool:
      vmImage: 'Ubuntu-16.04'
    
    steps:
    - task: DownloadPipelineArtifact@2
      inputs:
        buildType: 'current'
        artifactName: 'drop'
        targetPath: '$(System.ArtifactsDirectory)'

    - task: AzureResourceManagerTemplateDeployment@3
      inputs:
        deploymentScope: 'Resource Group'
        azureResourceManagerConnection: 'AzurePipelineConnection'
        subscriptionId: '961f9967-28e9-4924-992b-ad35af98451c'
        action: 'Create Or Update Resource Group'
        resourceGroupName: 'appDemo'
        location: 'East US'
        templateLocation: 'URL of the file'
        csmFileLink: 'https://raw.githubusercontent.com/mayhashah7/ContosoAir/master/deployment/azuredeploy.json'
        csmParametersFileLink: 'https://raw.githubusercontent.com/mayhashah7/ContosoAir/master/deployment/azuredeploy.parameters.json'
        overrideParameters: '-p_environment mayhashah'
        deploymentMode: 'Incremental'
      
    - task: AzureRmWebAppDeployment@4
      inputs:
        ConnectionType: 'AzureRM'
        azureSubscription: 'AzurePipelineConnection'
        appType: 'webApp'
        WebAppName: 'githubci-web-mayhashah'
        packageForLinux: '$(build.artifactstagingdirectory)/**/*.zip'  
